name: Build MineDigger
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Install build dependencies
        run: |
          sudo apt-get update -qq
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -qq libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
      - uses: actions/checkout@v2
      - name: Build project
        run: make PLATFORM=linux ARCH=64 BUILD=debug
  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1
      - name: Build project
        run: msbuild.exe ide/msvc/MineDigger.vcxproj -property:Configuration=Debug -property:Platform=x64
